"""Create / verify the dedicated read-only MariaDB/MySQL user.

Designed to work on any server this app ships to:
- Self-managed MariaDB/MySQL: connect with the admin (root/master) credentials
  the System Manager types into the dialog — used once, never stored.
- Managed databases (AWS RDS/Aurora, Lightsail managed DB, Azure, etc.):
  the master user usually CAN create users and grant SELECT, so the same flow
  works. Where it does not (restricted privileges, host rules, SUPER-less
  masters), create_user() returns success=False with the exact SQL to run
  manually plus the generated credentials, and the admin pastes them back via
  the manual-entry flow (api/settings.set_manual_db_user).

Host/port always come from site_config (frappe.conf), so nothing is
server-specific.
"""

import secrets

import frappe
import pymysql
from frappe import _

USER_PREFIX = "claude_ro_"


def get_db_connection_params() -> dict:
	return {
		"host": frappe.conf.db_host or "localhost",
		"port": int(frappe.conf.db_port or 3306),
	}


def generate_credentials() -> tuple[str, str]:
	user = USER_PREFIX + frappe.generate_hash(length=8).lower()
	password = secrets.token_urlsafe(24)
	return user, password


def get_manual_setup_sql(username: str, password: str, source_host: str = "%") -> str:
	"""The statements an admin runs manually when auto-creation is not possible
	(e.g. restricted managed databases)."""
	db_name = frappe.conf.db_name
	return (
		f"CREATE USER '{username}'@'{source_host}' IDENTIFIED BY '{password}';\n"
		f"GRANT SELECT ON `{db_name}`.* TO '{username}'@'{source_host}';\n"
		f"FLUSH PRIVILEGES;\n"
		f"-- verify:\n"
		f"SHOW GRANTS FOR '{username}'@'{source_host}';"
	)


def create_user(admin_user: str, admin_password: str, source_host: str = "%") -> dict:
	"""Create the read-only user using one-time admin credentials.

	Returns {"success": True, "username": ...} or
	{"success": False, "error": ..., "manual_sql": ..., "username": ..., "password": ...}
	"""
	params = get_db_connection_params()
	username, password = generate_credentials()
	db_name = frappe.conf.db_name

	conn = None
	try:
		conn = pymysql.connect(
			host=params["host"],
			port=params["port"],
			user=admin_user,
			password=admin_password,
			connect_timeout=10,
		)
		with conn.cursor() as cursor:
			cursor.execute(
				"CREATE USER %s@%s IDENTIFIED BY %s",
				(username, source_host, password),
			)
			# GRANT does not support placeholders for identifiers; db_name comes
			# from site_config and username is generated by us, not user input.
			cursor.execute(f"GRANT SELECT ON `{db_name}`.* TO %s@%s", (username, source_host))
			cursor.execute("FLUSH PRIVILEGES")
			cursor.execute("SHOW GRANTS FOR %s@%s", (username, source_host))
			grants = [row[0] for row in cursor.fetchall()]
		conn.commit()

		problem = check_grants_select_only(grants, db_name)
		if problem:
			return {
				"success": False,
				"error": problem,
				"manual_sql": get_manual_setup_sql(username, password, source_host),
				"username": username,
				"password": password,
			}

		store_credentials(username, password, mode="Automatic")
		return {"success": True, "username": username, "grants": grants}

	except pymysql.MySQLError as e:
		# managed DBs (RDS etc.) or host restrictions land here — give the admin
		# everything needed to do it manually
		return {
			"success": False,
			"error": f"{e.__class__.__name__}: {e}",
			"manual_sql": get_manual_setup_sql(username, password, source_host),
			"username": username,
			"password": password,
		}
	finally:
		if conn:
			conn.close()


def check_grants_select_only(grants: list[str], db_name: str) -> str | None:
	"""Return an error string if grants include anything beyond SELECT/USAGE."""
	allowed_verbs = ("GRANT SELECT ON", "GRANT USAGE ON")
	for g in grants:
		upper = g.upper()
		if not upper.startswith(allowed_verbs):
			return _("Unexpected grant found (user is not SELECT-only): {0}").format(g)
	return None


def verify_user(username: str, password: str) -> dict:
	"""Connect as the RO user, confirm SELECT works and grants are SELECT-only.
	Used after auto-creation, manual entry, and from the Verify button."""
	params = get_db_connection_params()
	db_name = frappe.conf.db_name
	conn = None
	try:
		conn = pymysql.connect(
			host=params["host"],
			port=params["port"],
			user=username,
			password=password,
			database=db_name,
			connect_timeout=10,
		)
		with conn.cursor() as cursor:
			cursor.execute("SELECT 1")
			cursor.execute("SHOW GRANTS FOR CURRENT_USER()")
			grants = [row[0] for row in cursor.fetchall()]

		problem = check_grants_select_only(grants, db_name)
		if problem:
			return {"success": False, "error": problem, "grants": grants}
		return {"success": True, "grants": grants}
	except pymysql.MySQLError as e:
		return {"success": False, "error": f"{e.__class__.__name__}: {e}"}
	finally:
		if conn:
			conn.close()


def store_credentials(username: str, password: str, mode: str):
	settings = frappe.get_doc("Claude AI Settings")
	settings.readonly_db_user = username
	settings.readonly_db_password = password
	settings.db_user_created = 1
	settings.db_user_created_on = frappe.utils.now_datetime()
	settings.db_user_mode = mode
	settings.save(ignore_permissions=True)
	frappe.db.commit()


def drop_user(admin_user: str, admin_password: str) -> dict:
	"""Drop the stored RO user (credential rotation / re-create). Admin creds
	are used once, never stored."""
	settings = frappe.get_doc("Claude AI Settings")
	username = settings.readonly_db_user
	if not username:
		return {"success": False, "error": _("No read-only user is configured.")}

	params = get_db_connection_params()
	conn = None
	try:
		conn = pymysql.connect(
			host=params["host"],
			port=params["port"],
			user=admin_user,
			password=admin_password,
			connect_timeout=10,
		)
		with conn.cursor() as cursor:
			cursor.execute("DROP USER IF EXISTS %s@%s", (username, "%"))
			cursor.execute("FLUSH PRIVILEGES")
		conn.commit()

		settings.readonly_db_user = ""
		settings.readonly_db_password = ""
		settings.db_user_created = 0
		settings.db_user_created_on = None
		settings.db_user_mode = ""
		settings.save(ignore_permissions=True)
		frappe.db.commit()
		return {"success": True}
	except pymysql.MySQLError as e:
		return {"success": False, "error": f"{e.__class__.__name__}: {e}"}
	finally:
		if conn:
			conn.close()
